[package]
name = "switcher-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "desktop-switcher"
path = "src/main.rs"

[dependencies]
switcher-core.workspace = true
switcher-backend-windows.workspace = true
switcher-backend-ddcutil.workspace = true
switcher-desktop.workspace = true
clap.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
toml.workspace = true
